/**
 * This file is generated by coconfig. Do not edit it directly.
 * Instead, edit the coconfig.js or coconfig.ts file in your project root.
 *
 * See https://github.com/gas-buddy/coconfig for more information.
 * @version coconfig@2.0.0
 */
import * as configModule from '@openapi-typescript-infra/coconfig';


const configItem = configModule.default || configModule.config || configModule;
const { configuration } = configItem && configItem['vitest.config.ts'];
const resolved = typeof configuration === 'function' ? configuration() : configuration;

// eslint-disable-next-line import/no-default-export
export default resolved;
